version: 2.1

executors:
  zig:
    docker:
      - image: ziglang/static-base:llvm13-x86_64-1
    working_directory: /zigenv

jobs:
  build:
    executor: zig
    steps:
      - checkout
      - run: /deps/local/bin/zig test zigenv/main_test.zig
