version: 2.1

executors:
  zig:
    docker:
      - image: cimg/base:2021.04
    working_directory: /zigenv

jobs:
  build:
    executor: zig
    steps:
      - checkout
      - run: curl https://ziglang.org/download/0.10.0/zig-linux-x86_64-0.10.0.tar.xz -O
      - run: tar xf zig-linux-x86_64-0.10.0.tar.xz
      - run: ./zig-linux-x86_64-0.10.0/zig test zigenv/main_test.zig
